# Generated by Django 4.2.28 on 2026-03-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=500)),
            ],
        ),
    ]
