# Generated by Django 4.2.28 on 2026-03-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIapp', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=500)),
                ('UserPassword', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
